### ISSUE TITLE
Connect MongoDB to Flask application

### ISSUE THREAD

**Issue by vivektallav** [Cloud1e/17155_1_Project#38]

**Comment by yiw008** [comment]
See commit [5c3046bf58bd721470de4431eff2cdce90060587](https://github.com/Cloud1e/17155_1_Project/commit/5c3046bf58bd721470de4431eff2cdce90060587) and  [a15d0c362186dbf74fbe9a6b49c08891176d98c7](https://github.com/Cloud1e/17155_1_Project/commit/a15d0c362186dbf74fbe9a6b49c08891176d98c7)

**Comment by yiw008** [comment]
@vivektallav Please check whether [a15d0c362186dbf74fbe9a6b49c08891176d98c7](https://github.com/Cloud1e/17155_1_Project/commit/a15d0c362186dbf74fbe9a6b49c08891176d98c7) works for you. If yes, you can close this issue.

**Comment by yiw008** [comment]
Approved on Slack at 0421 pm
